### ISSUE TITLE
Increase tick resolution

### ISSUE THREAD

**Issue by Engid** [chris-zen/hero-studio#14]
Howdy! Nick here from the `rust-dsp` group. I wasn't sure If I should open an issue or a PR, but I'm on my chromebook so an issue is easier 😅 

I've been reading an [interview with Paul Davis](https://www.admiralbumblebee.com/music/2018/02/20/Interview-with-Paul-Davis-of-Ardour-about-Ardour-6-and-more.html#question---when-going-through-the-code-i-noticed-something-called-super-clock-whats-that-it-sounds-super), the guy behind the Ardour DAW. He explains that using a super large integer such as [508032000](https://numbermatics.com/n/508032000/) for a "ticks-per-second" resolution to make dividing into any crazy bpm or time-signature really smooth.  

I suppose then this

https://github.com/chris-zen/hero-studio/blob/8cae5caa3c31f3028b89339d7ed0e8eafbeaae01/core/src/time/ticks.rs#L8

might then become
```rust
pub const TICKS_RESOLUTION: u64 = 2*2*2*2*2*2*2*2*2*2*3*3*3*3*5*5*5*7*7;
```

Cheers! 😄

**Comment by chris-zen** [comment]
Hey Nick,

thank you very much for the link to the interview. I really enjoyed reading it. I felt so identified. 
> It is incredible how much of a DAW is really about time - representing it, manipulating it, storing it 

When I started this project, one of the first things I wanted to address was timing. To be honest I didn't read much about the topic, and after reading the interview I realised that I was not in the wrong path with several of the decisions I took, which is great.

About the `TICKS_RESOLUTION` I remember that I was spending quite some time trying several things until I came up with that one. I tried to find the smaller number that gave me enough divisibility for the most common scenarios.

But using one that has been battle tested by Ardour seems a pretty good idea. After taking a look to the code I saw that it would affect to the `BarsTime` struct as it is using a `u16` to represent the ticks fraction, but other than that I was not able to identify any risk of overflow.

If you feel like creating a PR, please go ahead. Just remember that I haven't build Continuous Integration with travis yet, so you will need to run the tests yourself. The following tests will need an update:
```
    time::bars::test::to_ticks
    time::drift_correction::ticks::test::ticks_drift_correction_new
    time::drift_correction::ticks::test::ticks_drift_correction_next
    time::ticks::test::per_minute
```

Note that with the scare free time I have, I'd rather spend it with the work to remove locks and allocations right now, which is being quite challenging.

I'm labeling this issue as "good first issue" so you can have your first contribution if you like 😉
