### ISSUE TITLE
add screenshots of app to readme

### ISSUE THREAD

**Issue by amilajack** [chris-zen/hero-studio#19]
I think this would be a really helpful addition to the project for people who are trying to understand the project

**Comment by chris-zen** [comment]
Hi @amilajack, thanks for the feedback. I'll definitively do that when it gets a working UI. For now, I am working on the audio/MIDI engine, so there is no UI yet. I was experimenting with an electron UI prototype to test the communication between external UIs and the engine, but I haven't progress much on that side yet.
This is a very ambitious project, and it will take some time until I have a working UI. The priority for me now is to build an engine that can be used in different kind of applications.
