### ISSUE TITLE
Add continuous integration with Travis

### ISSUE THREAD

**Issue by chris-zen** [chris-zen/hero-studio#9]
Initially I am only interested in making sure everything builds and the tests pass for different platforms (Windows, Linux and MacOS).

**Comment by brainstorm** [comment]
I might just put this in place if you are happy with it?:

https://dev.to/hawkinjs/leveraging-travis-ci-for-continuous-deployment-to-publish-compiled-binaries-to-github-2k06

**Comment by chris-zen** [comment]
Please, go ahead, you are more than welcome 👏 👏 👏 
You are a collaborator already, so no need to fork, just a PR. Let me know if you need help to create secret tokens ;-)
